const mongoose = require('mongoose');

const requestItemSchema = new mongoose.Schema({
    id : String,
    name : String,
    sellingprice : String,
    startdatetime : String,
    enddatetime : String,
    name1 : String,
    strength : String,
    categoryid : String,
    manufacturerid : String,
    Deleted : String,
    manufacturercode : String,
    EUB : String,
    profitcenter : String,
    sunitid : String,
    tax : String,
    schedule : String,
    mrpitem : String,
    conversionqty : String,
    drugtype : String,
    itemcode : String,
    itemcheckcomplete : String,
    itemcheckincomplete : String,
    deletedby : String,
    unitid : String,
    type : String,
    narcotics : String,
    cssditem : String,
    consignment : String,
    approval : String,
    reusableitem : String,
    reusablecount : String,
    tempcatid : String,
    modifieddate : String,
    DiscountEligible : String,
    OperatorId : String,
    blocked : String,
    Claiming : String,
    CommodityCode : String,
    PurchasePrice : String,
    S_TAX : String,
    hsncode : String,
    CGST : String,
    SGST : String,
    IGST : String,
    specialisationid : String,
    pers_itemid : String,
    pers_categoryid : String,
    pers_manufacturerid : String,
});

const requestItemModel = new mongoose.model("request item", requestItemSchema);

module.exports = requestItemModel;